Repository mryel00/spyglass, pull requests merged in 2023-01, with the labels that each got.

#3 Update README with the URL of the stream
  README.md
Labels: documentation

#4 feat: Improve project structure and setup
  .github/workflows/build-and-package.yml
  .github/workflows/pull-request.yml
  .gitignore
  NOTICE
  README.md
  pyproject.toml
  requirements.txt
  run.py
  setup.cfg
  setup.py
  spyglass.py
  spyglass/__init__.py
  spyglass/__main__.py
  spyglass/camera.py
  spyglass/cli.py
  spyglass/server.py
Labels: documentation, enhancement

#5 Add snapshot url
  README.md
  spyglass/cli.py
  spyglass/server.py
Labels: enhancement

#6 refactor: Rename GitHub Action jobs
  .github/workflows/build-and-package.yml
  .github/workflows/pull-request.yml
Labels: enhancement

#9 docs: Add ADR about used encoder
  docs/adr/001_encoder.md
Labels: documentation
